# This workflow will generate updated metadata when changes are merged into the main branch

name: Update json feed in GH Pages
on:
  push:
    branches:
      - main

jobs:
  update_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: generate-json
        run: |
          python main/gen_skill_list.py
      - name: copy updated json
        run: |
          cp main/skills.json gh-pages/skills.json
      - uses: EndBug/add-and-commit@v7
        with:
          cwd: ./gh-pages
          branch: gh-pages
          add: skills.json
          message: "Automated Metadata Update"
